-- Tables --

DROP TABLE IF EXISTS `kz_records`;
CREATE TABLE `kz_records` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`map` VARCHAR(64) NOT NULL,
	`mappath` VARCHAR(16) NULL DEFAULT NULL,
	`time` DECIMAL(10,2) NULL DEFAULT NULL,
	`player` VARCHAR(32) NULL DEFAULT NULL,
	`country` VARCHAR(8) NULL DEFAULT NULL,
	`comm` VARCHAR(8) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	INDEX `map` (`map`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;